export const DOCUMENT_CREATED = 'DOCUMENT_CREATED';
export const DOCUMENT_CREATE_FAILED = 'DOCUMENT_CREATE_FAILED';
export const DOCUMENTS_READ = 'DOCUMENTS_READ';
export const VIEW_USER_DOCUMENTS_SUCCESS = 'VIEW_USER_DOCUMENTS_SUCCESS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_ROLE_SUCCESS = 'GET_ROLE_SUCCESS';
